# Generated by Django 5.0.2 on 2024-02-25 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventsLeft', models.IntegerField()),
                ('price', models.FloatField()),
                ('recurring', models.BooleanField()),
                ('renewDate', models.DateTimeField()),
                ('subscribeDate', models.DateTimeField()),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('eventQuantity', models.IntegerField()),
                ('type', models.IntegerField()),
                ('price', models.FloatField()),
                ('recurring', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('billAddress', models.CharField(blank=True, max_length=40)),
                ('billCity', models.CharField(blank=True, max_length=40)),
                ('billZip', models.CharField(blank=True, max_length=40)),
                ('billCountry', models.CharField(blank=True, max_length=40)),
                ('visitAddress', models.CharField(blank=True, max_length=40)),
                ('visitCity', models.CharField(blank=True, max_length=40)),
                ('visitZip', models.CharField(blank=True, max_length=40)),
                ('visitCountry', models.CharField(blank=True, max_length=40)),
                ('contactEmail', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('orgNumber', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('zip', models.CharField(max_length=5)),
                ('admins', models.ManyToManyField(blank=True, related_name='companies', to='api.emailaddress')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='api.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('book', models.TextField()),
                ('date', models.DateTimeField()),
                ('img', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('longDesciption', models.TextField()),
                ('shortDescription', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.company')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriptionOption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.subscriptionoption'),
        ),
    ]
