# Generated by Django 5.0.2 on 2024-02-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='option',
            new_name='subscriptionOption',
        ),
    ]
