# Generated by Django 5.0.2 on 2024-02-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='visitLatitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='visitLongitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
